//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.CantidadEnStock = 0;
            this.Precio = 0m;
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public short CantidadEnStock { get; set; }
        public decimal Precio { get; set; }
        public string Descripcion { get; set; }
    }
}
