//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.FirmaRecibido = false;
        }
    
        public int Id { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaEntregado { get; set; }
        public bool FirmaRecibido { get; set; }
    
        public virtual Cadete Cadete { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
