//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Total = 0m;
            this.PagoProcesado = false;
            this.SubTotal = 0m;
            this.CanitidadRecetasBlancas = 0;
            this.CantidadRecetasControladas = 0;
            this.DescuentoAplicado = 0m;
            this.Lineas = new HashSet<Linea>();
        }
    
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public decimal Total { get; set; }
        public int TarjetaId { get; set; }
        public bool PagoProcesado { get; set; }
        public decimal SubTotal { get; set; }
        public System.DateTime Fecha { get; set; }
        public short CanitidadRecetasBlancas { get; set; }
        public short CantidadRecetasControladas { get; set; }
        public decimal DescuentoAplicado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linea> Lineas { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
