//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> ArticuloSet { get; set; }
        public virtual DbSet<Factura> FacturaSet { get; set; }
        public virtual DbSet<Linea> LineaSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Delivery> DeliverySet { get; set; }
        public virtual DbSet<Cadete> CadeteSet { get; set; }
        public virtual DbSet<Categoria> CategoriaSet { get; set; }
        public virtual DbSet<Tarjeta> TarjetaSet { get; set; }

        public System.Data.Entity.DbSet<Core.Medicamento> Medicamentoes { get; set; }

        public System.Data.Entity.DbSet<Core.NoMedicamento> NoMedicamentoes { get; set; }
    }
}
